# Site settings
title: Activision Game Science
header-img: img/activision_game_science.png
email: william.kirwin@activision.com
description: "We are awesome."
baseurl: ""
url: "http://activisiongamescience.github.io"
github_username: ActivisionGameScience

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
gems: [jekyll-paginate]
